Repository aerospike/java-object-mapper, pull requests merged in 2021-04, with the labels that each got.

#1 Annotations package cleanup.
  src/main/java/com/aerospike/mapper/annotations/AerospikeBin.java
  src/main/java/com/aerospike/mapper/annotations/AerospikeEmbed.java
  src/main/java/com/aerospike/mapper/annotations/AerospikeExclude.java
  src/main/java/com/aerospike/mapper/annotations/AerospikeGetter.java
  src/main/java/com/aerospike/mapper/annotations/AerospikeKey.java
  src/main/java/com/aerospike/mapper/annotations/AerospikeOrdinal.java
  src/main/java/com/aerospike/mapper/annotations/AerospikeRecord.java
  src/main/java/com/aerospike/mapper/annotations/AerospikeReference.java
  src/main/java/com/aerospike/mapper/annotations/AerospikeSetter.java
  src/main/java/com/aerospike/mapper/annotations/ParamFrom.java
Labels: enhancement

#4 Bump dependencies versions and set project version to 1.0.0.
  pom.xml
Labels: dependencies

#2 Added a GitHub action for checking the build process
  .github/workflows/build.yml
Labels: enhancement

#3 tools.mappers package cleanup.
  src/main/java/com/aerospike/mapper/tools/mappers/DateMapper.java
  src/main/java/com/aerospike/mapper/tools/mappers/EnumMapper.java
  src/main/java/com/aerospike/mapper/tools/mappers/InstantMapper.java
  src/main/java/com/aerospike/mapper/tools/mappers/ListMapper.java
  src/main/java/com/aerospike/mapper/tools/mappers/ObjectEmbedMapper.java
  src/main/java/com/aerospike/mapper/tools/mappers/ObjectReferenceMapper.java
Labels: enhancement

#7 Added batch loading of objects
  README.md
  src/main/java/com/aerospike/mapper/annotations/AerospikeEmbed.java
  src/main/java/com/aerospike/mapper/tools/AeroMapper.java
  src/test/java/com/aerospike/mapper/AeroMapperBaseTest.java
  src/test/java/com/aerospike/mapper/BatchLoadTest.java
Labels: enhancement

#6 Tests directory cleanup.
  README.md
  src/test/java/com/aerospike/mapper/AdTechUseCaseExampleTest.java
  src/test/java/com/aerospike/mapper/AeroMapperArrayTests.java
  src/test/java/com/aerospike/mapper/AeroMapperBaseTest.java
  src/test/java/com/aerospike/mapper/AeroMapperConfigurationYamlTest.java
  src/test/java/com/aerospike/mapper/AeroMapperCustomConverterTest.java
  src/test/java/com/aerospike/mapper/AeroMapperDocExamples.java
  src/test/java/com/aerospike/mapper/AeroMapperExample.java
  src/test/java/com/aerospike/mapper/AeroMapperListOfObjectTransformTest.java
  src/test/java/com/aerospike/mapper/AeroMapperListTest.java
  src/test/java/com/aerospike/mapper/AeroMapperMapTest.java
  src/test/java/com/aerospike/mapper/AeroMapperObjectTransformTest.java
  src/test/java/com/aerospike/mapper/ArrayTest.java
  src/test/java/com/aerospike/mapper/CollectionMapperTest.java
  src/test/java/com/aerospike/mapper/ConstructorTest.java
  src/test/java/com/aerospike/mapper/InheritanceTest.java
  src/test/java/com/aerospike/mapper/KeysViaMethodTest.java
  src/test/java/com/aerospike/mapper/ListOfReferencesTest.java
  src/test/java/com/aerospike/mapper/MapTest.java
  src/test/java/com/aerospike/mapper/PartialRecordsTest.java
  src/test/java/com/aerospike/mapper/SubClassHierarchyTest.java
  src/test/java/com/aerospike/mapper/SubclassListTest.java
  src/test/java/com/aerospike/mapper/SubclassMapTest.java
  src/test/java/com/aerospike/mapper/TestAnonymousReferences.java
  src/test/java/com/aerospike/mapper/VirtualListExample.java
  src/test/java/com/aerospike/mapper/VirtualListTest.java
  src/test/java/com/aerospike/mapper/example/Application.java
  src/test/java/com/aerospike/mapper/example/ApplicationBase.java
  src/test/java/com/aerospike/mapper/example/JavaMapperApplication.java
  src/test/java/com/aerospike/mapper/example/NonJavaMapperApplication.java
  src/test/java/com/aerospike/mapper/example/model/Customer.java
  src/test/java/com/aerospike/mapper/example/model/Property.java
  src/test/java/com/aerospike/mapper/example/model/accounts/Account.java
  src/test/java/com/aerospike/mapper/example/model/accounts/PortfolioAccount.java
  src/test/java/com/aerospike/mapper/model/Account.java
  src/test/java/com/aerospike/mapper/model/Person.java
  src/test/java/com/aerospike/mapper/model/Product.java
Labels: enhancement

#8 Bump jackson dataformat yaml from 2.12.2 to 2.12.3.
  pom.xml
Labels: dependencies

#11 Add Maven source plugin version.
  pom.xml
Labels: dependencies

#16 Documentation enhancements
  README.md
  images/complexObjectGraph.png
  images/objectInstantiation.png
  src/main/java/com/aerospike/mapper/tools/AeroMapper.java
  src/main/java/com/aerospike/mapper/tools/ThreadLocalKeySaver.java
  src/test/java/com/aerospike/mapper/DateCustomConverterTest.java
  src/test/java/com/aerospike/mapper/MultipleParameterSetterTest.java
  src/test/java/com/aerospike/mapper/example/NonJavaMapperApplication.java
Labels: documentation

#12 Tools package cleanup
  src/main/java/com/aerospike/mapper/tools/AeroMapper.java
  src/main/java/com/aerospike/mapper/tools/ClassCache.java
  src/main/java/com/aerospike/mapper/tools/ClassCacheEntry.java
  src/main/java/com/aerospike/mapper/tools/DeferredObjectLoader.java
  src/main/java/com/aerospike/mapper/tools/DeferredOperation.java
  src/main/java/com/aerospike/mapper/tools/GenericTypeMapper.java
  src/main/java/com/aerospike/mapper/tools/OperationParameters.java
  src/main/java/com/aerospike/mapper/tools/PropertyDefinition.java
  src/main/java/com/aerospike/mapper/tools/ResultsUnpacker.java
  src/main/java/com/aerospike/mapper/tools/TypeMapper.java
  src/main/java/com/aerospike/mapper/tools/TypeUtils.java
  src/main/java/com/aerospike/mapper/tools/ValueType.java
  src/main/java/com/aerospike/mapper/tools/VirtualList.java
  src/main/java/com/aerospike/mapper/tools/configuration/ClassConfig.java
  src/main/java/com/aerospike/mapper/tools/configuration/Configuration.java
  src/main/java/com/aerospike/mapper/tools/mappers/ArrayMapper.java
  src/main/java/com/aerospike/mapper/tools/mappers/ListMapper.java
  src/main/java/com/aerospike/mapper/tools/mappers/MapMapper.java
Labels: enhancement

#13 Readme table of contents
  README.md
Labels: documentation

#19 Corrections to the documentation (tfaulkes).
  README.md
Labels: documentation

#21 Bump to 1.1.0
  README.md
  pom.xml
Labels: dependencies

#22 Added javadoc configuration.
  pom.xml
Labels: dependencies

#24 Update README.md file:
  README.md
Labels: documentation
