Repository aerospike/java-object-mapper, pull requests merged in 2024-07, with the labels that each got.

#160 FMWK-468 Allow send key classes to use PK instead of Bin
  README.md
  src/main/java/com/aerospike/mapper/annotations/AerospikeKey.java
  src/main/java/com/aerospike/mapper/tools/AeroMapper.java
  src/main/java/com/aerospike/mapper/tools/ClassCacheEntry.java
  src/main/java/com/aerospike/mapper/tools/ReactiveAeroMapper.java
  src/main/java/com/aerospike/mapper/tools/configuration/ClassConfig.java
  src/main/java/com/aerospike/mapper/tools/configuration/KeyConfig.java
  src/main/java/com/aerospike/mapper/tools/converters/MappingConverter.java
  src/test/java/com/aerospike/mapper/UsePKColumnInsteadOfBinForKeyTest.java
  src/test/java/com/aerospike/mapper/reactive/ReactiveUsePKColumnInsteadOfBinForKeyTest.java
Labels: enhancement

#161 FMWK-467 Issue using refs with yaml file
  src/main/java/com/aerospike/mapper/tools/configuration/ClassConfig.java
  src/main/java/com/aerospike/mapper/tools/configuration/ReferenceConfig.java
  src/main/java/com/aerospike/mapper/tools/utils/TypeUtils.java
Labels: bug

#158 FMWK-466 Add Insert Only Method
  src/main/java/com/aerospike/mapper/tools/AeroMapper.java
  src/main/java/com/aerospike/mapper/tools/IAeroMapper.java
  src/main/java/com/aerospike/mapper/tools/IReactiveAeroMapper.java
  src/main/java/com/aerospike/mapper/tools/ReactiveAeroMapper.java
  src/test/java/com/aerospike/mapper/InsertOnlyTest.java
  src/test/java/com/aerospike/mapper/reactive/ReactiveInsertOnlyTest.java
Labels: bug

#162 Bump dependencies and set version to 2.5.0
  README.md
  pom.xml
Labels: dependencies
